apiRules:
- include: 
    uidRegex: ^SF
    type: Namespace
- exclude:
    uidRegex: .*
    type: Namespace
- exclude:
    uidRegex: ^SF.InputModule.Controls.*
    type: Type
- exclude:
    uidRegex: ^SF.InputModule.Controls.*
    type: Class
- exclude:
    uidRegex: ^SF.InputModule.Controls
    type: Class
- exclude:
    uidRegex: ^SF.InputModule.Controls.*
    type: Struct
